services:

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgis
    ports:
      - "9090:9090"
    links:
      - postgis

  postgis:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  #    volumes:
  #      - postgis:/var/lib/postgresql/data

  desmos:
    image: desmos:latest
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/dbtest
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/dbtest
      LOGGING_LEVEL_ES_IN2_DESMOS: DEBUG
      CLIENT_ORGANIZATIONID: VATES-S9999999E
      DLT_ADAPTER_PROVIDER: digitelts
      DLT_ADAPTER_INTERNAL_DOMAIN: http://dlt-adapter:8080
      DLT_ADAPTER_EXTERNAL_DOMAIN: http://dlt-adapter:8080
      TX_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos:8080/api/v1/notifications/dlt
      TX_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
      BROKER_PROVIDER: scorpio
      BROKER_EXTERNAL_DOMAIN: http://scorpio:9090
      BROKER_INTERNAL_DOMAIN: http://scorpio:9090
      NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos:8080/api/v1/notifications/broker
      NGSI_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
    ports:
      - "9091:8080"
    links:
      - dlt-adapter
      - scorpio
      - postgres

  postgres:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest
  #    volumes:
  #      - postgres:/var/lib/postgresql/data

  dlt-adapter:
    image: quay.io/digitelts/dlt-adapter:1.3
    environment:
      PRIVATE_KEY: 0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346
      DOME_EVENTS_CONTRACT_ADDRESS:
      RPC_ADDRESS: https://red-t.alastria.io/v0/9461d9f4292b41230527d57ee90652a6
      DOME_PRODUCTION_BLOCK_NUMBER: 0
      ISS: 0x40b0ab9dfd960064fb7e9fdf77f889c71569e349055ff563e8d699d8fa97fa90
    ports:
      - "9092:8080"

#volumes:
#  postgis:
#  postgres: