global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'DesmosMetrics'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'desmos-node-a:8080' ]
        labels:
          application: 'Desmos-Api'